### ISSUE TITLE
Title bar does not appear and I would like to see the title bar

### ISSUE THREAD

**Issue by derwan** [Milly/compact_menu_2#17]
I see a menu that writes "Firefox" in the titlebar. A compact menu icon in the navigation bar is sufficient and I use it. Can there be an option to see the titlebar?

**Comment by TheBlackSun** [comment]
-> Right Click, show/hide Bookmarks Bar.
I guess the Bug's still there, since the Update isn't published yet - do you want it to look like that...?
It will fix itself on Browser Restart though, it's just a Bug. See -> https://github.com/Milly/compact_menu_2/issues/14
I had an Idea of an Option to implement, either keep the 'new' Titlebar with Button or replace it with the old one without Button.

**Comment by derwan** [comment]
Thank you. It would be nice to see the title bar. Thanks for providing this addon for firefox.

**Comment by TheBlackSun** [comment]
It's just a BUG! It will 'reset' on each Start of the Browser! Why did you close it yet?
Re-created -> https://github.com/Milly/compact_menu_2/issues/19
